### ISSUE TITLE
Split panes?

### ISSUE THREAD

**Issue by delaneyj** [vaheqelyan/svelte-grid#5]
Is there a way to bind 2 panes together so when one resizes the other responds automatically to +/- the changed dimension?

**Comment by vaheqelyan** [comment]
Hi. Currently no.
it will be a bit unusual to include this feature in this component, but I think it will be possible.when there is not enough row for the widget it will move to the next column.instead of moving to the next column it can resize as much as possible.when it is fully covered, it will move to the next column.I will consider this in the future
