### ISSUE TITLE
`Adjust` method fails when #cols < #items

### ISSUE THREAD

**Issue by clozach** [vaheqelyan/svelte-grid#76]
I made a variant of your [Fill space REPL](https://svelte-grid.now.sh/examples/fill-space) to demonstrate this issue.

> https://svelte.dev/repl/87ca5a4411fb45a6bc8039fa62cfb204

This version uses fixed sizes for all items, sequential integers for the `id`s, and removes the `fillSpace` toggle.

### Steps to Reproduce

1. Load this [REPL](https://svelte.dev/repl/87ca5a4411fb45a6bc8039fa62cfb204)

    **Expected:** 20 items, numbered sequentially `#1` through `#20`
    **Actual:** Only 10 items, display (2 rows missing), and `#20` is in `#6`'s place

2. Click on any item

    **Expected:** Nothing. Clicking on an item without moving or resizing it should have no impact.
    **Actual:** Missing items appear, and everything flows into the correct place. (If item clicked is `#20`, it remains out of order.)

3. Change `const numCols = 10` to `const numCols = 19`. Note that the same issues are present. ❌

4. Change `const numCols = 19` to `const numCols = 20`. Note how the issue seems "fixed". ✅

**Comment by vaheqelyan** [comment]
i have a good solution to fix this.
https://github.com/vaheqelyan/svelte-grid/blob/master/src/utils/item.js#L29

**Comment by vaheqelyan** [comment]
Here is the reason https://github.com/vaheqelyan/svelte-grid/blob/master/src/utils/item.js#L153
The third argument is the `items` (All elements have `h: 1` and `y: 0`.), which is wrong, instead I need to pass `res`

Another solution. We can pass the length of the matrix instead of calling the `getRowCount` function
https://github.com/vaheqelyan/svelte-grid/blob/master/src/utils/item.js#L29
